### ISSUE TITLE
Memory Leaks with d3d9on12 layer in DX9 Application

### ISSUE THREAD

**Issue by tkaushik97** [microsoft/D3D9On12#72] opened 2023-11-09 07:02 UTC
I am encountering memory leaks in my DX9 application when using the d3d9on12 layer. The memory leaks seem to be related to the d3d9on12 layer, as I'm not able to see call stacks related to my own code when using UMDH memory report.

Upon further investigation, I've noticed that some traces suggest leaks in the destructor of classes that contain DX9 smart pointers like IDirect3DVertexDeclaration9Ptr, or in FreeResource function where I set these smart pointers to NULL.

![image](https://github.com/microsoft/D3D9On12/assets/46860777/55197958-5913-436d-93e0-6c95be9766be)

Seeking for your help regarding this.

**Comment by vdwtanner** [comment] 2024-01-19 20:24
Hard to say just from looking here, but a couple options that come to mind are
* you aren't calling Release in your smart pointer
*  the underlying d3d9 object could still be in use by the device so the device itself is holding the reference.

Regarding the linked issue, d3d9on12 pre-allocates the various heaps that it uses, and right now it defaults to reserving space for D3D12_MAX_SHADER_VISIBLE_DESCRIPTOR_HEAP_SIZE_TIER_1 views (~32MB). Sampler heap also defaults to D3D12_MAX_SHADER_VISIBLE_SAMPLER_HEAP_SIZE. These two allocations alone are probably where most of that usage is coming from. This is by design so that we basically never have to swap out the bound descriptor heap. This is generally fine for most applications since 9on12 is expected to only be running on newer hardware with more memory available than when applications were originally authored for d3d9, but where it is not (generally an x86 application that was already pressing up against the 2GB memory limit) there are a couple of options available:

* use reg keys to test for a more appropriate setting (good if this is a issue affecting a very small / controlled set of machines)
  * Create a new key: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Direct3D\Direct3D9on12 for x64, HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Direct3D\Direct3D9on12 for x86
  * Create a new DWORD value: MaxSRVHeapSize and choose a value that you think is more reasonable for your use case. 2048 is substantially smaller and still leaves a decent number of SRVs available for small use cases, so that could be a good starting point.
* For large impact situations, shimming via appcompat is possible.
* It's also possible to try marking the application as LargeAddressAware, but [there could be dragons there](https://stackoverflow.com/a/22745579/2910057)

**Comment by lindexi** [comment] 2024-11-04 12:16
According to @hiteshwpfmsft 's analysis (https://github.com/dotnet/wpf/issues/7704#issuecomment-2437374394) and my analysis (https://github.com/dotnet/wpf/issues/7704#issuecomment-2249742202), this issues is plaguing WPF developers.

My question is: Do all current D3D9 applications require more memory? Or is this just a statistical issue, where the memory that should be attributed to the graphics card is being counted towards the application process?

**Comment by vdwtanner** [comment] 2024-11-05 19:01
Hi @lindexi, based on the conversations that we had with the wpf team, the increased memory for WPF is not a memory leak, and is instead the pre-allocation of resources that d3d9on12 does as a performance optimization. This is by design, and we don't have plans to change that now. Based on the comments, it looks like only ~50MB of increased usage. I can understand that that is annoying when a simpler app may not benefit from the tradeoff, but that increase doesn't seem like something that would be a huge issue on modern systems where 9on12 would be in use.

> Do all current D3D9 applications require more memory?
Yes, this pre-allocation happens per d3d9 device that is created by the application. So if you have multiple d3d9 devices hanging around you'd be paying the cost multiple times.

> Or is this just a statistical issue, where the memory that should be attributed to the graphics card is being counted towards the application process?
I don't believe that is the case. GPU memory usage should be properly tracked as d3d9on12 is just built on top of d3d12.

Closing this for now as the original commenter hasn't followed up and the issue in question now is by design.

**Closed by vdwtanner** 2024-11-05 19:01 UTC

**Comment by lindexi** [comment] 2024-11-06 00:51
@vdwtanner Thank you. 

> Based on the comments, it looks like only ~50MB of increased usage

No, according to feedback from many developers, the increase is more than 100MB of memory.

**Comment by shennig** [comment] 2024-12-16 14:11
Hi, 
the increase in more complex apps with larger graphics dependencies is much higher, as described in this thread of mine https://community.intel.com/t5/Graphics/High-memory-consumption-in-WPF-App-with-Intel-graphics/m-p/1518684 
Meanwhile we have adopted a workaround which uses software rendering instead of hardware rendering for affected systems. With this, the apps don't crash but a massively worse performance is the result. 
So, we have a workaround, but no satisfactory solution!
Best regards,
Sascha

**Comment by lindexi** [comment] 2024-12-17 01:38
> Hi, the increase in more complex apps with larger graphics dependencies is much higher, as described in this thread of mine https://community.intel.com/t5/Graphics/High-memory-consumption-in-WPF-App-with-Intel-graphics/m-p/1518684 Meanwhile we have adopted a workaround which uses software rendering instead of hardware rendering for affected systems. With this, the apps don't crash but a massively worse performance is the result. So, we have a workaround, but no satisfactory solution! Best regards, Sascha

@vdwtanner Can I ask any ideas?
